[UTStatsLiteDamage.utslDamage]
;if set to False 100 damage to a player with 2 health will be counted as 2 rather than 100 damage
bIncludeAllDamageDone=False
ImpactHammerDamageType=impact
ImpactHammerAltDamageType=impact
EnforcerDamageType=shot
EnforcerAltDamageType=shot
BioRifleDamageType=Corroded
BioRifleAltDamageType=Corroded
ShockRifleDamageType=jolted
ShockRifleAltDamageType=jolted
PulseRifleDamageType=Pulsed
PulseRifleAltDamageType=zapped
RazorDamageType=shredded
RazorAltDamageType=RipperAltDeath
MinigunDamageType=shot
MinigunAltDamageType=shot
FlakCannonDamageType=shredded
FlakCannonAltDamageType=FlakDeath
RocketLauncherDamageType=RocketDeath
RocketLauncherAltDamageType=GrenadeDeath
SniperRifleDamageType=shot
SniperRifleAltDamageType=shot
RedeemerDamageType=RedeemerDeath
RedeemerAltDamageType=RedeemerDeath
DecapitatedDamageType=Decapitated