[UTStatsLiteDamage.utslDamage]
;if set to False 100 damage to a player with 2 health will be counted as 2 rather than 100 damage
bIncludeAllDamageDone=False
PulseProjectileDamageType='Pulsed'
PulseBeamnDamageType='zapped'
RazorPrimaryDamageType='shredded'
RazorAltDamageType='RipperAltDeath'
FlakShellDamageType='FlakDeath'
FlakPrimaryDamageType='shredded'
BioRifleDamageType='Corroded'
RocketGrenadeDamageType= 'GrenadeDeath'
RocketLauncherDamageType= 'RocketDeath'
ShockRifleDamageType='jolted'
RedeemerDamageType='RedeemerDeath'
