[UTStatsLiteDamage.utslDamage]
;if set to False 100 damage to a player with 2 health will be counted as 2 rather than 100 damage
bIncludeAllDamageDone=False
bOnlyTrackWeaponDamage=True
ImpactHammerName=Impact Hammer
ImpactHammerDamageType=impact
ImpactHammerAltDamageType=impact
EnforcerName=Enforcer
EnforcerDamageType=shot
EnforcerAltDamageType=shot
BioRifleName=GES BioRifle
BioRifleDamageType=Corroded
BioRifleAltDamageType=Corroded
ShockRifleName=Shock Rifle
ShockRifleDamageType=jolted
ShockRifleAltDamageType=jolted
PulseRifleName=Pulse Gun
PulseRifleDamageType=Pulsed
PulseRifleAltDamageType=zapped
RipperName=Ripper
RipperDamageType=shredded
RipperAltDamageType=RipperAltDeath
bCheckBothRipperDamageTypes=False
MinigunName=Minigun
MinigunDamageType=shot
MinigunAltDamageType=shot
FlakCannonName=Flak Cannon
FlakCannonDamageType=shredded
FlakCannonAltDamageType=FlakDeath
bCheckBothFlakCannonDamageTypes=False
RocketLauncherName=Rocket Launcher
RocketLauncherDamageType=RocketDeath
RocketLauncherAltDamageType=GrenadeDeath
SniperRifleName=Sniper Rifle
SniperRifleDamageType=shot
SniperRifleAltDamageType=shot
RedeemerName=Redeemer
RedeemerDamageType=RedeemerDeath
RedeemerAltDamageType=RedeemerDeath